<a href="https://colab.research.google.com/github/LOWERCAS3/PyTorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.8975, 0.8535, 0.0382, 0.5038, 0.1149, 0.0269, 0.5981],
        [0.1081, 0.3703, 0.2088, 0.2313, 0.0847, 0.2272, 0.6593],
        [0.4417, 0.5313, 0.4472, 0.2684, 0.9285, 0.3567, 0.2516],
        [0.1069, 0.6560, 0.8661, 0.9987, 0.0019, 0.9774, 0.6454],
        [0.3706, 0.9226, 0.3149, 0.1078, 0.8556, 0.1818, 0.2037],
        [0.8931, 0.2173, 0.9800, 0.0518, 0.9981, 0.0133, 0.7023],
        [0.7018, 0.7704, 0.8489, 0.4932, 0.4493, 0.9730, 0.6815]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
another_tensor = torch.rand(1, 7)
# Perform matrix multiplication 
matmul_tensor = torch.matmul(tensor, another_tensor.T)
matmul_tensor, matmul_tensor.shape

(tensor([[1.6602],
         [1.3112],
         [1.5617],
         [2.5271],
         [1.6476],
         [1.8750],
         [2.6448]]), torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOMSEED = 0

# Create two random tensors
torch.manual_seed(RANDOMSEED)
tensor_A = torch.rand(2, 3)

torch.manual_seed(RANDOMSEED)
tensor_B = torch.rand(2, 3)

print(f"tensor_A: \n{tensor_A}")
print(f"tensor_B: \n{tensor_B}")

# Matrix multiply tensors
print(f"\nOutput of matrix multiplication of tensor_A and tensor_B: \n{torch.matmul(tensor_A, tensor_B.T)}")

tensor_A: 
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor_B: 
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

Output of matrix multiplication of tensor_A and tensor_B: 
tensor([[0.8443, 0.3578],
        [0.3578, 0.5140]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
RANDOMSEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available else "cpu"
print(device)

# Create two random tensors on GPU
torch.manual_seed(RANDOMSEED)
tensor_A = torch.rand(2, 3, device=device)

torch.manual_seed(RANDOMSEED)
tensor_B = torch.rand(2, 3, device=device)

print(f"tensor_A: \n{tensor_A}")
print(f"tensor_B: \n{tensor_B}")

cuda
tensor_A: 
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor_B: 
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
print(f"Output of matmul as tensor: \n{tensor_C}")
print(f"Output tensor shape: {tensor_C.shape}")

Output of matmul as tensor: 
tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')
Output tensor shape: torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f"Max of output tensor: {tensor_C.max()}")
# Find min
print(f"Min of output tensor: {tensor_C.min()}")

Max of output tensor: 1.4577524662017822
Min of output tensor: 0.8358409404754639


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"Index of max of output tensor: {tensor_C.argmax()}")

# Find arg min
print(f"Index of min of output tensor: {tensor_C.argmin()}")

Index of max of output tensor: 3
Index of min of output tensor: 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes
print(f"tensor_D: \n{tensor_D}")
print(f"tensor_D shape: {tensor_D.shape}")
print(f"tensor_E: \n{tensor_E}")
print(f"tensor_E shape: {tensor_E.shape}")

tensor_D: 
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor_D shape: torch.Size([1, 1, 1, 10])
tensor_E: 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
tensor_E shape: torch.Size([10])
