<a href="https://colab.research.google.com/github/LOWERCAS3/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [ ]:
# 1.12.1+cu113 
# 1.12.1 is the version and cu113 is the cuda version
# CUDA is what enables us to run pytorch code in Nvidia GPU/

## Introductions to tensors

### Creating tensors
#### PyTorch Tensors are  created using ```torch.Tensor()``` 
Doc: https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
#Number of dimnesions of scalar
scalar.ndim 

0

In [ ]:
#Get tensor back as Python int
scalar.item()

10

In [ ]:
# Vector
vector = torch.tensor([12, 11])
vector

tensor([12, 11])

In [ ]:
#Number of dimensions of vector
vector.ndim

1

In [ ]:
vector.size()

torch.Size([2])

In [ ]:
vector[0]

tensor(12)

In [ ]:
# MATRIX 
MATRIX = torch.tensor([[10, 11], [25,34]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.size()

torch.Size([2, 2])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([25, 34])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[11, 23, 43], 
                        [32, 43, 32],
                        [76, 54, 98]]])
TENSOR

tensor([[[11, 23, 43],
         [32, 43, 32],
         [76, 54, 98]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[11, 23, 43], 
                        [32, 43, 32],
                        [76, 54, 98]], 
                       [[1, 2 ,3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[11, 23, 43],
         [32, 43, 32],
         [76, 54, 98]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random tensors

Why random tensors?

Random tensors are using as a starting tensor or an input tensor for a neural network.
These random tensor are full of random values and are adjusted by neural network after learning in order to represent data better.


`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

Doc: https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
# Create  a random tensor of size(4, 6) (or shape can be used interchangebly)
random_tensor = torch.rand(3,2,4,6)
random_tensor

tensor([[[[0.2629, 0.2754, 0.2106, 0.4473, 0.5634, 0.9499],
          [0.3510, 0.1103, 0.8008, 0.6465, 0.0952, 0.5989],
          [0.5196, 0.3454, 0.7268, 0.8098, 0.6805, 0.1277],
          [0.2057, 0.3088, 0.5268, 0.7052, 0.7075, 0.7791]],

         [[0.9654, 0.1357, 0.8964, 0.6529, 0.1828, 0.6673],
          [0.7276, 0.8909, 0.0946, 0.1160, 0.9145, 0.4932],
          [0.2757, 0.7383, 0.8215, 0.4224, 0.2449, 0.6238],
          [0.8681, 0.0564, 0.3423, 0.4538, 0.3515, 0.4398]]],


        [[[0.9961, 0.7332, 0.2040, 0.5915, 0.4460, 0.0500],
          [0.4426, 0.9863, 0.8206, 0.8415, 0.8891, 0.9306],
          [0.7828, 0.4974, 0.7436, 0.8622, 0.7063, 0.5933],
          [0.1384, 0.1310, 0.4684, 0.5668, 0.1109, 0.5609]],

         [[0.4321, 0.5402, 0.3974, 0.6999, 0.3383, 0.6976],
          [0.4554, 0.5968, 0.8827, 0.0596, 0.1766, 0.2090],
          [0.5303, 0.9282, 0.9121, 0.4292, 0.2543, 0.2446],
          [0.2491, 0.4730, 0.7989, 0.5848, 0.0198, 0.1356]]],


        [[[0.1986, 0.6734, 0

### Image tensor

An image tensor is a tensor with height, width , colour channels.

Height and width represents the dimensions of the image.

Colour channels represents the number of colour used. eg: (R, G, B) - 3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(2, 3, 4))
zeros # zero tensors are usually used to null out the values of all the values by multiplying it with a random tensor 

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all ones
ones =  torch.ones(size=(4, 2 ,2))
ones

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

### Creating a range of tensors and tensors-like

###tensor.arange

`torch.arange` is used to give range (Works similar to `for i in range(0, n)`)

Doc: https://pytorch.org/docs/stable/generated/torch.arange.html

###tensor-like

`torch.zeros_like` is used to create tensors similar in shape to one given in input

There are alot of different functions for like eg full_like, ones_like, rand_like etc

Doc: https://pytorch.org/docs/stable/generated/torch.zeros_like.html

In [ ]:
# Use torch.arange()
torch.arange(0, 19)
arange_tensor = torch.arange(start=0,end=100, step=9)
arange_tensor

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [ ]:
# Create tensors like
zero_copy = torch.zeros_like(input=arange_tensor)
zero_copy

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
 3 big errors for pytorch and deeplearning are:
 1. Tensors not right datatype
 2. Tensors not right shape
 3. Tensors not the right device.

In [ ]:
float_32_tensor = torch.tensor( [3.0, 4.0, 5.0],
                                dtype = None, # What datatype is the tensor (e.g. float16 or float32)
                                device = None,# What device is your tensor on (e.g. cuda , CPU, TPU)
                                requires_grad = False) # Whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [ ]:
int_32_tensor = torch.tensor([3, 4, 5], dtype = torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
float_16_tensor*int_32_tensor

tensor([ 9., 16., 25.], dtype=torch.float16)

### Getting information from tensor {Tensor Attribute}
1. Tensors not right datatype - to get a datatype from tensor, can use `tensor.dtype`
2. Tensors not right shape - to get a shape from tensor, can use `tensor.shape`
3. Tensors not the right device. - to get device from tenson (tup, cpu, gpu), can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8250, 0.9532, 0.9415, 0.4576],
        [0.2853, 0.1671, 0.8629, 0.8975],
        [0.5290, 0.6719, 0.3951, 0.0734]])

In [ ]:
# Finding details about tensor
some_tensor.dtype, some_tensor.device, some_tensor.shape

(torch.float32, device(type='cpu'), torch.Size([3, 4]))

### Manipulating tensors {Tensor Operations}

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Martix Multiplication

In [ ]:
# Create a tensor
tnsr = torch.tensor([2, 3, 4])
tnsr

tensor([2, 3, 4])

In [ ]:
# Adding tensor by int
tnsr + 10

tensor([12, 13, 14])

In [ ]:
# Multiplying tensor by float
tnsr * 10.0

tensor([20., 30., 40.])

In [ ]:
# Subtracting tensor by int
tnsr - 1

tensor([1, 2, 3])

In [ ]:
# PyTorch build-in function
torch.mul(tnsr, 10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two rules for matrix multiplications 
1. The **inner dimensions** must match
2. The result will be the the shape of **outer dimension**


In [ ]:
# Element wise multiplication
print(tnsr, "*" , tnsr)
print(f"Equals {tnsr * tnsr}")

tensor([2, 3, 4]) * tensor([2, 3, 4])
Equals tensor([ 4,  9, 16])


In [ ]:
# Matrix multiplication
torch.matmul(tnsr, tnsr)

tensor(29)

In [ ]:
%%time
value = 0
for i in range(len(tnsr)):
    value += tnsr[i] * tnsr[i]
print(value)

tensor(29)
CPU times: user 2.84 ms, sys: 1.08 ms, total: 3.92 ms
Wall time: 3.11 ms


In [ ]:
%%time
print(torch.matmul(tnsr, tnsr))

tensor(29)
CPU times: user 677 µs, sys: 0 ns, total: 677 µs
Wall time: 618 µs


In [ ]:
t1 = torch.rand(2,2,3)
t1

tensor([[[0.4099, 0.2166, 0.9259],
         [0.8262, 0.1886, 0.3670]],

        [[0.8499, 0.6802, 0.4195],
         [0.0277, 0.9186, 0.4508]]])

In [ ]:
print(torch.matmul(t1, torch.rand(2,3,2)))

tensor([[[0.3519, 0.5918],
         [0.5069, 0.7797]],

        [[0.6939, 1.4528],
         [0.4070, 1.1012]]])


### Working with shape errors

In [ ]:
tensor_A =  torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) is short-hand for torch.matmul(tensor_A, tensor_B)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

### Tensor matrices can be transposed!!

Transpose function in PyTorch switches the shape 
(x, y) will become (y, x)

In [ ]:
# Trasposing elements of tensor_B

tensor_B_transposed = tensor_B.T 
tensor_B_transposed.shape

torch.Size([2, 3])

In [ ]:
# This works because the tensor_B is transposed to match the shape of tensor tensor_A
torch.matmul(tensor_A, tensor_B_transposed)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#Visualize, Visualize, Visualize
print(f"Original shapes: \ntensor_A -> {tensor_A.shape} \ntensor_B -> {tensor_B.shape}")
print(f"Transposing tensor_A since inner dimensions do not match")
print(f"New shape of transposed tensor_A \ntensor_A.T -> {tensor_A.shape}")
print(f"Multiplying tensor_A.T and tensor_B")
print("Output :")
output = torch.matmul(tensor_A.T, tensor_B)
print(output)
print(f"Shape of Output tensor -> {output.shape}")

Original shapes: 
tensor_A -> torch.Size([3, 2]) 
tensor_B -> torch.Size([3, 2])
Transposing tensor_A since inner dimensions do not match
New shape of transposed tensor_A 
tensor_A.T -> torch.Size([3, 2])
Multiplying tensor_A.T and tensor_B
Output :
tensor([[ 76, 103],
        [100, 136]])
Shape of Output tensor -> torch.Size([2, 2])


### Tensor Aggregation
Finding min, max, mean, sum, etc

In [ ]:
# Creating tensor 
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Find the mean
# Note:- tensor.mean() expects the tensor datatype to be float32 datatype
print(x.dtype)
print(x.type(torch.float32))
torch.mean(x.type(torch.float32)).type(torch.int32), x.type(torch.float32).mean()

torch.int64
tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])


(tensor(45, dtype=torch.int32), tensor(45.))

### Finding position of value that is min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the position in tensor that ha maximum value with argmax() -> returns the index of max element
torch.argmax(x), x.argmax() 

(tensor(9), tensor(9))

In [ ]:
# Finding the position in tensor that has minimum value with argmin()
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - Reshape an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - Combine multiple tensors on toem of each other (vstack) or side by side (hstack).

Doc -https://pytorch.org/docs/stable/generated/torch.stack.html
* Squeeze - Remove all the `1` dimensions from a tensor.
* Unsqueezing - Add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
# Creating a tensor
import torch
x = torch.arange(1., 10., 1)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Add an extra dimension
# The below example reshapes/divides 3 matrices each with 3 elements
# Just applying the reshape doesnot changes the original tensor but rather give the o/p as the changed tensor.
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing a view of a tensor changes the original tensor (because a view of tensor shares the same memory as the original input)
z [:, 0] = 5
print(f"{z, x}")
z[:, 0] = 1

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))


In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a single tensor
x_reshaped = x.reshape(1, 9)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension in x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order (changes the view)
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dims) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x = torch.rand(2, 3, 5)
x_permuted = torch.permute(x, (2, 0, 1))
print(f"Original tensor: \n{x}")
print(f"Permuted tensor: \n{x_permuted}")

# Changing values in original tensor
print(f"Original value : {x[0, 1, 0]}")
x[0, 1, 0] = 1

# Affect on permuted tensor
print(f"Permuted tensor with changed value : \n{x_permuted}")

Original tensor: 
tensor([[[0.6256, 0.5417, 0.1866, 0.8615, 0.4234],
         [0.3655, 0.5875, 0.3496, 0.7192, 0.4596],
         [0.1002, 0.4849, 0.2629, 0.1481, 0.9141]],

        [[0.7432, 0.2214, 0.5051, 0.6928, 0.0265],
         [0.3916, 0.6973, 0.0908, 0.5030, 0.1496],
         [0.1908, 0.8493, 0.0540, 0.9255, 0.8392]]])
Permuted tensor: 
tensor([[[0.6256, 0.3655, 0.1002],
         [0.7432, 0.3916, 0.1908]],

        [[0.5417, 0.5875, 0.4849],
         [0.2214, 0.6973, 0.8493]],

        [[0.1866, 0.3496, 0.2629],
         [0.5051, 0.0908, 0.0540]],

        [[0.8615, 0.7192, 0.1481],
         [0.6928, 0.5030, 0.9255]],

        [[0.4234, 0.4596, 0.9141],
         [0.0265, 0.1496, 0.8392]]])
Original value : 0.3654567003250122
Permuted tensor with changed value : 
tensor([[[0.6256, 1.0000, 0.1002],
         [0.7432, 0.3916, 0.1908]],

        [[0.5417, 0.5875, 0.4849],
         [0.2214, 0.6973, 0.8493]],

        [[0.1866, 0.3496, 0.2629],
         [0.5051, 0.0908, 0.0540]],

    

### Indexing in Tensors (selecting data from tensor)
Indexing for tensors in PyTorch is similar to indexing in NumPy

In [ ]:
import torch
x = torch.arange(1,19).reshape(2,3,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]), torch.Size([2, 3, 3]))

In [ ]:
# Let's index on outer dimension (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle dimension (dim=1)
x[0, 0] # This can also be represent as x[0][1]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner dimension (dim=2)
x[0, 0, 0]

tensor(1)

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [ ]:
x[:, :, 0]

tensor([[ 1,  4,  7],
        [10, 13, 16]])

In [ ]:
x[:, 0, 0]

tensor([ 1, 10])

In [ ]:
x[:, 2, 2]

tensor([ 9, 18])

In [ ]:
x[:, :, 2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [ ]:
x[0, 2, 2]

tensor(9)

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, but I want in PyTorch (or vise-versa)
 * NumPy to PyTorch -> `torch.from_numpy(ndarray)`
 * PyTorch to NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array  to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
# warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
tensor = torch.from_numpy(array) 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> do it again -> again -> again....`

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.


In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9203, 0.0060, 0.8773, 0.3862],
        [0.0182, 0.2687, 0.7090, 0.5380],
        [0.0862, 0.5216, 0.1619, 0.4731]])
tensor([[0.5605, 0.1517, 0.6777, 0.4475],
        [0.2884, 0.6045, 0.1944, 0.7786],
        [0.3476, 0.7724, 0.0111, 0.9925]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random bu reproducible tensors.
import torch

# Set a random seed
RANDOM_SEED = 42 # This can be any random value.
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # Needs to be reseeded to create same tensor(in notebook)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running PyTorch objects on the GPUs
### Getting a GPU
1. Use Google colab
2. Use personal GPU setup
3. Use cloud computing providers e.g. GCP, AWS, Azure

In [ ]:
# Checking GPU details on colab
!nvidia-smi

Sun Oct  2 01:37:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Checking GPU access for PyTorch
import torch

torch.cuda.is_available()

True

**NOTE** --->  For PyTorch since it is capable of running compute on the GPU and CPU, it's best practice ot setup device agnostic code.
E.g. run on GPU if available else default to CPU 

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to GPU

NumPy only works on CPU hence for the computation using NumPy, tensors are required to be moved back to CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')